image: node:11

cache:
  paths:
    - node_modules
    - .yarn-cache

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn-cache
    - yarn install
  script:
    - yarn test

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - yarn config set cache-folder .yarn-cache
    - yarn install
  script:
    - git remote add gh-pages git@github.com:blank-blade/mff-tools.git
    - yarn deploy --ci --remote gh-pages --branch gh-pages 1> /dev/null
